name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project (e.g., My Cool App)'
        required: true
        default: '{{cookiecutter.project_name}}'  
      project_slug:
        description: 'Slug version of the project (e.g., my_cool_app)'
        required: true
        default: '{{cookiecutter.project_slug}}'  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: "{{ cookiecutter.project_name }}"
      PROJECT_SLUG: "{{ cookiecutter.project_slug }}"
      DOCKERHUB_USERNAME: "{{ cookiecutter.dockerhub_username }}"
      DOCKERHUB_TOKEN: "${{ '{{' }} secrets.DOCKERHUB_TOKEN {{ '}}' }}"
      GKE_CLUSTER: "{{ cookiecutter.gke_cluster }}"
      GKE_LOCATION: "{{ cookiecutter.gke_location }}"
      GKE_PROJECT: "{{ cookiecutter.gke_project }}"
      SNYK_TOKEN: "test"
      SNYK_ORG: "{{ cookiecutter.snyk_org }}"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Snyk Maven scan
        uses: snyk/actions/maven@master
        with:
          args: test --all-projects --org=TODO

      - name: Log in to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build & Push Docker image
        run: |
          docker build -t docker.io/$DOCKERHUB_USERNAME/$PROJECT_SLUG:latest .
          docker push docker.io/$DOCKERHUB_USERNAME/$PROJECT_SLUG:latest

      - name: Run Snyk Docker scan
        uses: snyk/actions/docker@master
        with:
          image: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_SLUG }}:latest
          args: test --org=TODO

      - name: Set up GCloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "TODO"

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: $GKE_CLUSTER
          location: $GKE_LOCATION
          project_id: $GKE_PROJECT

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
